d <- read.csv("agentic_hangout/data_taxonomy_standardized.csv")
cols <- c("order", "name_original", "name")
d <- d[cols]
# Non-Coleoptera examples (name should = order)
noncol <- head(d[d$order != "Coleoptera" & !is.na(d$order) & d$order != "", ], 6)
# Coleoptera examples (name should = name_original)
col <- head(d[d$order == "Coleoptera", ], 6)
cat("--- Non-Coleoptera (name standardized to order) ---\n")
print(noncol)
cat("\n--- Coleoptera (name unchanged, finer taxonomy kept) ---\n")
print(col)
